# Generated by Django 4.2.23 on 2025-08-20 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutTotal', '0002_category_parent_alter_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 5, 23, 35, 571144, tzinfo=datetime.timezone.utc)),
        ),
    ]
