# Generated by Django 4.2.23 on 2025-08-23 04:47

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutTotal', '0003_alter_category_description_alter_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 4, 47, 6, 633592, tzinfo=datetime.timezone.utc)),
        ),
    ]
