# Generated by Django 4.2.23 on 2025-08-23 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutTotal', '0004_alter_recipe_content_alter_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 17, 41, 58, 617048, tzinfo=datetime.timezone.utc)),
        ),
    ]
